class Anime {
  final int id;
  final String name;
  final String imageP;
  final String imageH;
  final String genre;
  final String season;
  final String state;
  final String chapter;
  final String description;
  final String autor;
  final String studio;
  final String year;
  final List<String> dAnime; //disponible en anime
  final List<String> dManga; //disponible en manga
  final List<String> characters;
  final String urlTrailer; //url del trailer

  Anime(
    this.id,
    this.name,
    this.imageP,
    this.imageH,
    this.genre,
    this.season,
    this.state,
    this.chapter,
    this.description,
    this.autor,
    this.studio,
    this.year,
    this.dAnime,
    this.dManga,
    this.characters,
    this.urlTrailer,
  );
}

Anime getAnime(int id) {
  return animes.firstWhere((anime) => anime.id == id);
}

List<Anime> getAllanimes() {
  return animes;
}

final List<Anime> animes = [
  Anime(
    0,
    "My Hero Academy",
    "assets/heroAcademy.webp",
    "assets/horizontal/heroAcademyH.jpg",
    "Shonen",
    "Temporada 7",
    "Emision",
    "159",
    "En un mundo donde casi todos poseen superpoderes llamados Quirks, Izuku Midoriya, un chico sin poderes, sueña con ser héroe. Su vida cambia cuando conoce a su ídolo All Might, quien le hereda su poder y lo impulsa a entrenar en la UA, una prestigiosa academia para futuros héroes.",
    "Kohei Horikoshi",
    "Estudio BONES",
    "2016",
    ["Crunchyroll", "Netflix", "Hulu"],
    ["VIZ Media"],
    ["Izuku Midoriya", "Katsuki Bakugo", "All Might", "Ochaco Uraraka"],
    "https://www.youtube.com/watch?v=EPVkcwyLQQ8",
  ),
  Anime(
    1,
    "Hunter X Hunter",
    "assets/hunterX.jpg",
    "assets/horizontal/hunterXH.webp",
    "Shonen",
    "Temporada 6",
    "Hiatus",
    "148",
    "Hunter x Hunter cuenta la historia de Gon Freecss, un niño que busca convertirse en Hunter para encontrar a su padre. En su viaje conoce a Killua, Kurapika y Leorio, con quienes enfrentará desafíos, enemigos poderosos y misterios, mientras descubre el verdadero significado de la amistad y la aventura.",
    "Yoshihiro Togashi",
    "Nippon Animation",
    "1999",
    ["Crunchyroll", "Netflix", "Amazon Prime Video"],
    ["Manga Plus", "VIZ Media"],
    ["Gon Freecss", "Killua Zoldyck", "Kurapika", "Leorio Paradinight"],
    "https://www.youtube.com/watch?v=F_YR1T_MdCI",
  ),
  Anime(
    2,
    "Shokugeki no Soma",
    "assets/shokugeki.jpg",
    "assets/horizontal/shokugekiH.jpg",
    "Gourmet",
    "Temporada 5",
    "Finalizado",
    "86",
    "Soma Yukihira, un joven apasionado por la cocina, entra en la prestigiosa academia culinaria Totsuki, donde los estudiantes compiten en intensos duelos gastronómicos llamados Shokugeki. Allí deberá superar rivales de gran talento para convertirse en un chef de élite.",
    "Yūto Tsukuda, Shun Saeki",
    "Estudio J.C.Staff",
    "2015",
    ["Crunchyroll", "Netflix", "Hulu"],
    ["VIZ Media"],
    ["Soma Yukihira", "Erina Nakiri", "Megumi Tadokoro", "Takumi Aldini"],
    "https://www.youtube.com/watch?v=--v6zWSR_Ko",
  ),
  Anime(
    3,
    "Kimetsu no Yaiba",
    "assets/kimetsu.webp",
    "assets/horizontal/kimetsuH.png",
    "Shonen",
    "Temporada 4",
    "Emision",
    "68",
    "Kimetsu no Yaiba cuenta la historia de Tanjiro Kamado, un joven bondadoso que vive en las montañas con su familia. Tras regresar un día y encontrar a toda su familia asesinada por demonios, descubre que su hermana Nezuko ha sobrevivido, pero ha sido transformada en demonio. Decidido a salvarla y vengar a su familia, Tanjiro se une a los Cazadores de Demonios, enfrentándose a criaturas sobrenaturales y peligros mortales. La serie explora la fuerza del vínculo familiar, la lucha entre el bien y el mal, y la determinación frente a la adversidad.",
    "Koyoharu Gotouge",
    "Ufotable",
    "2019",
    ["Crunchyroll", "Netflix", "Amazon Prime Video"],
    ["Manga Plus", "VIZ Media"],
    [
      "Tanjiro Kamado",
      "Nezuko Kamado",
      "Zenitsu Agatsuma",
      "Inosuke Hashibira",
    ],
    "https://www.youtube.com/watch?v=VQGCKyvzIM4",
  ),
  /*Anime(
    4,
    "Fullmetal Alchemist: Brotherhood",
    "assets/fmab.jpg",
    "assets/horizontal/fmabH.jpg",
    "Shonen",
    "Temporada 1",
    "Finalizado",
    "64",
    "Dos hermanos alquimistas, Edward y Alphonse Elric, buscan la Piedra Filosofal para recuperar sus cuerpos tras un fallo en un ritual de alquimia. La serie explora temas de sacrificio, ética y la naturaleza del poder.",
    "Hiromu Arakawa",
    "Bones",
    "2009",
    ["Crunchyroll", "Netflix"],
    ["Square Enix"],
    ["Edward Elric", "Alphonse Elric", "Roy Mustang", "Winry Rockbell"],
    "https://www.youtube.com/watch?v=Q8ts1jTqWfM",
  ),
  Anime(
    5,
    "Attack on Titan",
    "assets/attackOnTitan.jpg",
    "assets/horizontal/attackOnTitanH.jpg",
    "Seinen",
    "Temporada 4",
    "Finalizado",
    "87",
    "La humanidad vive dentro de murallas gigantes para protegerse de titanes devoradores de humanos. Eren Jaeger y sus amigos luchan por descubrir la verdad detrás de los titanes y la historia del mundo.",
    "Hajime Isayama",
    "MAPPA / Wit Studio",
    "2013",
    ["Crunchyroll", "Funimation"],
    ["Kodansha"],
    ["Eren Jaeger", "Mikasa Ackerman", "Armin Arlert", "Levi Ackerman"],
    "https://www.youtube.com/watch?v=MGRm4IzK1SQ",
  ),
  Anime(
    6,
    "One Piece",
    "assets/onePiece.jpg",
    "assets/horizontal/onePieceH.jpg",
    "Shonen",
    "Temporada 20+",
    "Emision",
    "1000",
    "Monkey D. Luffy y su tripulación de piratas buscan el legendario tesoro 'One Piece' para convertirlo en el Rey de los Piratas. Aventuras, camaradería y luchas épicas a través de mares y islas únicas.",
    "Eiichiro Oda",
    "Toei Animation",
    "1999",
    ["Crunchyroll", "Netflix", "Funimation"],
    ["Shueisha"],
    ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Sanji"],
    "https://www.youtube.com/watch?v=GkKkq4QG4rE",
  ),
  Anime(
    7,
    "Naruto Shippuden",
    "assets/narutoShippuden.jpg",
    "assets/horizontal/narutoShippudenH.jpg",
    "Shonen",
    "Temporada 20",
    "Finalizado",
    "500",
    "Naruto Uzumaki, un ninja joven con el sueño de ser Hokage, continúa su viaje enfrentando amenazas mayores y descubriendo secretos sobre su origen y el poder del zorro demonio sellado en él.",
    "Masashi Kishimoto",
    "Pierrot",
    "2007",
    ["Crunchyroll", "Netflix"],
    ["Shueisha", "VIZ Media"],
    ["Naruto Uzumaki", "Sasuke Uchiha", "Sakura Haruno", "Kakashi Hatake"],
    "https://www.youtube.com/watch?v=7qf8Bv1YdN8",
  ),
  Anime(
    8,
    "Death Note",
    "assets/deathNote.jpg",
    "assets/horizontal/deathNoteH.jpg",
    "Thriller",
    "Miniserie",
    "Finalizado",
    "37",
    "Un estudiante encuentra un cuaderno que mata a quien cuyo nombre escribas. Conocido como Kira, intenta crear un mundo ideal mientras el brillante detective L intenta detenerlo. Juego mental entre justicia y moralidad.",
    "Tsugumi Ohba, Takeshi Obata",
    "Madhouse",
    "2006",
    ["Netflix", "Crunchyroll"],
    ["Shueisha"],
    ["Light Yagami", "L (Lawliet)", "Misa Amane", "Ryuk"],
    "https://www.youtube.com/watch?v=ifX8sJX9Y2A",
  ),
  Anime(
    9,
    "Steins;Gate",
    "assets/steinsGate.jpg",
    "assets/horizontal/steinsGateH.jpg",
    "Sci-Fi",
    "Temporada 1",
    "Finalizado",
    "24",
    "Un grupo de jóvenes descubre cómo enviar mensajes al pasado, desencadenando cambios temporales peligrosos. El científico Rintarou Okabe debe arreglar las líneas temporales para evitar consecuencias catastróficas.",
    "Chiyoji Mutsumi / 5pb.",
    "White Fox",
    "2011",
    ["Crunchyroll", "Funimation"],
    ["Kadokawa"],
    ["Rintarou Okabe", "Kurisu Makise", "Mayuri Shiina", "Itaru Hashida"],
    "https://www.youtube.com/watch?v=F1FfYwq6xqI",
  ),
  Anime(
    10,
    "Code Geass: Lelouch of the Rebellion",
    "assets/codeGeass.jpg",
    "assets/horizontal/codeGeassH.jpg",
    "Mecha",
    "Temporada 2",
    "Finalizado",
    "50",
    "Lelouch obtiene un poder llamado Geass que le permite controlar a otros. Lo usa para liderar una rebelión contra el imperio de Britannia y crear un mundo justo para su hermana, en un juego de tácticas y traiciones.",
    "Ichirō Ōkouchi, Gorō Taniguchi",
    "Sunrise",
    "2006",
    ["Crunchyroll", "Netflix"],
    ["Kadokawa"],
    ["Lelouch Lamperouge", "C.C.", "Suzaku Kururugi", "Nunnally vi Britannia"],
    "https://www.youtube.com/watch?v=9q4p3sY3m0c",
  ),
  Anime(
    11,
    "Cowboy Bebop",
    "assets/cowboyBebop.jpg",
    "assets/horizontal/cowboyBebopH.jpg",
    "Space",
    "Temporada 1",
    "Finalizado",
    "26",
    "Cazarrecompensas espaciales viajan en la nave Bebop, enfrentando criminales, su pasado y el sentido de la soledad. Serie elegante con mezcla de jazz, acción y drama existencial.",
    "Hajime Yatate",
    "Sunrise",
    "1998",
    ["Crunchyroll", "Netflix"],
    ["Kadokawa"],
    ["Spike Spiegel", "Jet Black", "Faye Valentine", "Edward"],
    "https://www.youtube.com/watch?v=8hNM5g2YzKA",
  ),
  Anime(
    12,
    "Neon Genesis Evangelion",
    "assets/evangelion.jpg",
    "assets/horizontal/evangelionH.jpg",
    "Mecha",
    "Temporada 1",
    "Finalizado",
    "26",
    "Adolescentes pilotan mechas llamados EVAs para defender a la humanidad de seres llamados Ángeles, mientras se exploran profundas crisis psicológicas y religiosas.",
    "Hideaki Anno",
    "Gainax / Khara",
    "1995",
    ["Crunchyroll", "Netflix"],
    ["Kadokawa"],
    ["Shinji Ikari", "Rei Ayanami", "Asuka Langley Soryu", "Gendo Ikari"],
    "https://www.youtube.com/watch?v=zlD6Yf9Jp44",
  ),
  Anime(
    13,
    "JoJo's Bizarre Adventure: Stardust Crusaders",
    "assets/jojo.jpg",
    "assets/horizontal/jojoH.jpg",
    "Shonen",
    "Temporada 3",
    "Finalizado",
    "48",
    "Jotaro Kujo y sus aliados viajan desde Japón hasta Egipto para enfrentar a Dio y salvar a la familia Joestar, usando poderes llamados Stands en enfrentamientos creativos y extravagantes.",
    "Hirohiko Araki",
    "David Production",
    "2014",
    ["Crunchyroll", "Netflix"],
    ["Shueisha"],
    ["Jotaro Kujo", "Joseph Joestar", "Noriaki Kakyoin", "Muhammad Avdol"],
    "https://www.youtube.com/watch?v=9mJ8n4S8X7E",
  ),*/
];
